# Generated by Django 4.2.7 on 2023-12-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
